### ISSUE TITLE
Weather 1 Day Off

### ISSUE THREAD

**Issue by williamlauzon** [lfroms/clouds#72]
I am currently experiencing an issue where the weather is one day off of what is on Environment Canada’s website. For example, the app is showing Saturday’s weather for Sunday, and Sunday’s weather for Monday. The date and time are correct on my phone, and the WeatherCAN app on my phone matches what I see on Environment Canada. I’d really love to be able to use this app as it is gorgeous, so I’m hoping this can be resolved. Thank you in advance!

**Comment by williamlauzon** [comment]
Update: The issue seems to be gone this morning, so it looks like the issue might only occur when it is late at night.

**Comment by williamlauzon** [comment]
In case it helps, when I looked last night, it was showing “TODAY” as Saturday (last night was Friday). When I looked this morning, it was still showing “TODAY” as Saturday, which is now correct.

**Comment by lfroms** [comment]
Hey @williamlauzon, thanks for flagging this. This is actually partly due to the data returned from Environment Canada (the WeatherCAN app uses a private internal EC API and not the MSC Datamart as Clouds/Nimbus use, so the private API may already have this fixed). In **rare** occasions, the days returned from the Datamart are mislabelled and are offset by 1 day. There is also, unfortunately, no good way of parsing the data since only weekday names are used in the raw data as opposed to timestamps.

That being said, the actual logic to parse the dates occurs in [lfroms/nimbus](https://github.com/lfroms/nimbus/blob/master/app/services/weather/environment_canada/factories/daily_factory.rb#L41), so I'll create a corresponding issue there. I'll keep an eye out for the next occurrence and confirm the logic.

**Comment by williamlauzon** [comment]
Hi @lfroms, thanks so much for the quick reply! I really appreciate you looking in to this and the effort you've put into making this great app! It's too bad that the issue is on the MSC Datamart side, but hopefully it will be fixed by them at some point. Again, thank you for your work!
